// ════════════════════════════════════════════════════════════════════════
//  BALKOUN · buyer's guides (content)
//  Editorial text for the /guides/ pages in Arabic, English and German.
//  Each guide: slug (shared by all languages), tag, title, lede, sections
//  (heading + paragraphs), and FAQ. Written for Syrian buyers, tenants and
//  the diaspora. General guidance, not legal advice: every guide says so.
// ════════════════════════════════════════════════════════════════════════
const t = (ar, en, de) => ({ ar, en, de });

export const GUIDES = [
  {
    slug: "verify-deed", homeIndex: 0,
    tag: t("الطابو", "Title deed", "Grundbuch"),
    title: t("كيف تتحقق من سند الملكية في السجل العقاري", "How to verify a title deed at the land registry in Syria", "So prüfen Sie ein Grundbuchdokument in Syrien"),
    lede: t("قبل أن تدفع أي عربون، تأكد بنفسك أن العقار مسجّل باسم البائع، وأنه خالٍ من الرهون والحجوزات والدعاوى. هذه هي الخطوات، من البداية إلى النهاية.",
      "Before you pay any deposit, confirm for yourself that the property is registered in the seller's name and free of mortgages, seizures and lawsuits. Here are the steps from start to finish.",
      "Bevor Sie eine Anzahlung leisten, prüfen Sie selbst, ob die Immobilie auf den Verkäufer eingetragen und frei von Hypotheken, Pfändungen und Klagen ist. Hier die Schritte von Anfang bis Ende."),
    sections: [
      { h: t("ما الذي تطلبه من البائع", "What to ask the seller for", "Was Sie vom Verkäufer verlangen"),
        p: [t("اطلب نسخة عن سند الملكية (الطابو) وعن هوية المالك المسجّل. قارن الاسم والاسم الكامل ورقم العقار (رقم المحضر والمنطقة العقارية) بين السند والهوية. إذا كان البائع وكيلاً، اطلب الوكالة الأصلية وتحقق من أنها تخوّله البيع تحديداً وأنها ما زالت سارية.",
            "Ask for a copy of the title deed (tabu) and the ID of the registered owner. Compare the full name and the property numbers (plot and cadastral zone) between the deed and the ID. If the seller is an agent, ask for the original power of attorney and check that it specifically allows a sale and is still valid.",
            "Verlangen Sie eine Kopie des Grundbuchauszugs (Tabu) und den Ausweis des eingetragenen Eigentümers. Vergleichen Sie den vollständigen Namen und die Grundstücksnummern (Parzelle und Katasterzone) zwischen Auszug und Ausweis. Handelt ein Bevollmächtigter, verlangen Sie die Originalvollmacht und prüfen Sie, ob sie ausdrücklich einen Verkauf erlaubt und noch gültig ist.")] },
      { h: t("بيان القيد العقاري: الورقة الأهم", "The registry extract: the document that matters", "Der aktuelle Grundbuchauszug: das wichtigste Papier"),
        p: [t("الورقة التي تحميك هي «بيان قيد عقاري» حديث من المديرية العامة للمصالح العقارية (السجل العقاري) في المحافظة. يمكن لأي شخص طلبه برقم العقار. يبيّن اسم المالك الحالي، حصته، ونوع العقار، وأهم ما فيه: الإشارات المسجلة على الصحيفة العقارية مثل الرهن، الحجز الاحتياطي أو التنفيذي، إشارة الدعوى، أو حق الانتفاع لطرف آخر.",
            "The document that protects you is a recent registry extract from the General Directorate of Cadastral Affairs (the land registry) in the governorate. Anyone can request it with the property number. It shows the current owner, their share, the type of property and, most importantly, any notes recorded on the property sheet: a mortgage, a precautionary or executive seizure, a pending lawsuit, or a right of use held by someone else.",
            "Das Dokument, das Sie schützt, ist ein aktueller Auszug der Generaldirektion für Katasterangelegenheiten (Grundbuchamt) des Gouvernements. Jeder kann ihn mit der Grundstücksnummer beantragen. Er zeigt den aktuellen Eigentümer, seinen Anteil, die Art der Immobilie und vor allem alle Vermerke auf dem Grundbuchblatt: Hypothek, vorläufige oder vollstreckbare Pfändung, anhängige Klage oder ein Nutzungsrecht Dritter."),
          t("اطلب البيان بتاريخ حديث، ويفضّل في اليوم الذي توقّع فيه العقد الابتدائي، لأن الإشارات قد تُسجّل في أي وقت. بيان قديم بأسابيع لا يكفي.",
            "Get the extract dated as close as possible to the day you sign the preliminary contract, because a note can be recorded at any time. An extract that is weeks old is not enough.",
            "Der Auszug sollte möglichst vom Tag der Vertragsunterzeichnung stammen, denn Vermerke können jederzeit eingetragen werden. Ein wochenalter Auszug reicht nicht.")] },
      { h: t("ما الذي تتفقّده في البيان", "What to check on the extract", "Was Sie im Auszug prüfen"),
        p: [t("أولاً: أن اسم المالك مطابق للبائع أو لموكّله. ثانياً: أن الحصة المعروضة هي الحصة المسجلة كاملة، فبعض العقارات مملوكة بحصص لعدة ورثة، ولا يجوز لأحدهم بيع الكل. ثالثاً: أن الصحيفة خالية من الإشارات، أو أن أي إشارة موجودة سيتم رفعها قبل نقل الملكية وبحضورك. رابعاً: أن وصف العقار (شقة، أرض، مساحة، طابق) يطابق ما تراه على الأرض.",
            "First, the owner's name matches the seller or the person who gave them power of attorney. Second, the share on offer is the full registered share: some properties are held in shares by several heirs, and one of them cannot sell the whole. Third, the sheet has no notes, or any existing note will be lifted before the transfer, in your presence. Fourth, the description (apartment, land, size, floor) matches what you saw on site.",
            "Erstens: Der Eigentümername stimmt mit dem Verkäufer oder dem Vollmachtgeber überein. Zweitens: Der angebotene Anteil ist der volle eingetragene Anteil; manche Immobilien gehören mehreren Erben anteilig, und einer allein kann nicht alles verkaufen. Drittens: Das Blatt trägt keine Vermerke, oder ein vorhandener Vermerk wird vor der Übertragung in Ihrer Anwesenheit gelöscht. Viertens: Die Beschreibung (Wohnung, Grundstück, Fläche, Etage) entspricht dem, was Sie vor Ort gesehen haben.")] },
      { h: t("متى تدفع العربون", "When to pay the deposit", "Wann Sie die Anzahlung leisten"),
        p: [t("لا تدفع أي مبلغ قبل رؤية بيان القيد الحديث والتحقق منه. وحين تدفع، اجعل الدفع مقابل عقد بيع ابتدائي مكتوب يذكر رقم العقار، الثمن الكامل، ما دُفع، موعد الفراغ (نقل الملكية) لدى الجهة المختصة، ومصير العربون إذا تراجع أحد الطرفين. الأفضل أن يُوقّع العقد أمام كاتب العدل أو بحضور محامٍ.",
            "Pay nothing before you have seen and checked a recent extract. When you do pay, pay against a written preliminary sale contract that states the property number, the full price, what was paid, the date of the transfer at the competent office, and what happens to the deposit if either side withdraws. Ideally sign it before a notary or with a lawyer present.",
            "Zahlen Sie nichts, bevor Sie einen aktuellen Auszug gesehen und geprüft haben. Zahlen Sie dann nur gegen einen schriftlichen Vorvertrag, der die Grundstücksnummer, den vollen Preis, das Gezahlte, den Termin der Eigentumsübertragung bei der zuständigen Behörde und das Schicksal der Anzahlung bei Rücktritt einer Seite festhält. Am besten vor einem Notar oder mit einem Anwalt unterschreiben.")] },
    ],
    faq: [
      t(["هل يمكنني طلب بيان قيد عقاري لعقار لا أملكه؟", "نعم. بيان القيد وثيقة عامة تُطلب برقم العقار من السجل العقاري في المحافظة، ولا يحتاج طالبها إلى إذن المالك."],
        ["Can I request a registry extract for a property I do not own?", "Yes. The extract is a public document requested with the property number at the governorate's land registry, and you do not need the owner's permission."],
        ["Kann ich einen Grundbuchauszug für eine fremde Immobilie beantragen?", "Ja. Der Auszug ist ein öffentliches Dokument, das mit der Grundstücksnummer beim Grundbuchamt des Gouvernements beantragt wird, ohne Erlaubnis des Eigentümers."]),
      t(["البائع يقول إن الطابو «قيد التسجيل». هل أشتري؟", "لا تدفع قبل أن يكتمل التسجيل ويصدر بيان قيد باسمه. الوعد بتسجيل قريب ليس ضماناً."],
        ["The seller says the deed is 'being registered'. Should I buy?", "Do not pay before the registration is complete and an extract exists in their name. A promise of imminent registration is not a guarantee."],
        ["Der Verkäufer sagt, der Eintrag sei 'in Bearbeitung'. Soll ich kaufen?", "Zahlen Sie nicht, bevor der Eintrag abgeschlossen ist und ein Auszug auf seinen Namen vorliegt. Das Versprechen eines baldigen Eintrags ist keine Sicherheit."]),
    ],
  },
  {
    slug: "deed-types", homeIndex: 1,
    tag: t("الطابو", "Title deed", "Grundbuch"),
    title: t("الطابو الأخضر، الأسهم، حكم المحكمة، الوكالة: ما الفرق وما المخاطر", "Green tabu, shares, court ruling, power of attorney: what each means and the risks", "Grünes Grundbuch, Anteile, Gerichtsurteil, Vollmacht: Bedeutung und Risiken"),
    lede: t("كل إعلان على بلكون يذكر حالة الطابو. هذا الدليل يشرح ما تعنيه كل حالة، وأي منها يمكن تسجيلها باسمك، وأين تكمن المخاطر.",
      "Every listing on Balkoun states the deed status. This guide explains what each status means, which of them can be registered in your name, and where the risks are.",
      "Jede Anzeige auf Balkoun nennt den Grundbuchstatus. Dieser Ratgeber erklärt, was jeder Status bedeutet, welcher auf Ihren Namen eingetragen werden kann und wo die Risiken liegen."),
    sections: [
      { h: t("الطابو الأخضر", "Green tabu", "Grünes Grundbuch"),
        p: [t("سند ملكية مسجّل في السجل العقاري، والعقار فيه مستقل بصحيفة عقارية خاصة (شقة مفرزة أو أرض بمحضر مستقل). هذا أعلى مستوى من الأمان: تُنقل الملكية باسمك مباشرة في السجل العقاري، ويمكن رهنه والتصرف به بحرية. إذا كان بمقدورك، اشترِ طابو أخضر.",
            "A deed registered at the land registry, where the property has its own property sheet (a subdivided apartment or a plot with its own number). This is the highest level of security: ownership is transferred directly into your name at the registry, and the property can be mortgaged and sold freely. If you can, buy green tabu.",
            "Ein im Grundbuch eingetragener Titel, bei dem die Immobilie ein eigenes Grundbuchblatt hat (aufgeteilte Wohnung oder Parzelle mit eigener Nummer). Das ist die höchste Sicherheitsstufe: Das Eigentum wird direkt auf Ihren Namen übertragen, die Immobilie kann frei belastet und verkauft werden. Wenn möglich, kaufen Sie grünes Grundbuch.")] },
      { h: t("الأسهم (الحصص السهمية)", "Shares", "Anteile"),
        p: [t("العقار هنا غير مفرز: البناء كله مسجّل كمحضر واحد بعدد من الأسهم (2400 سهم عادة)، وما تشتريه هو عدد من الأسهم لا شقة محددة في السجل. الاتفاق على أن هذه الأسهم «تقابل» الشقة الفلانية اتفاق بين الشركاء وليس قيداً رسمياً. ينتشر هذا في مناطق كثيرة وقد يكون مقبولاً، لكنه يعني أنك شريك في العقار كله، وأن الإفراز قد لا يحصل، وأن أي شريك قد يطلب إزالة الشيوع.",
            "The property is not subdivided: the whole building is one registered plot divided into a number of shares (usually 2,400), and what you buy is a number of shares, not a specific apartment in the registry. The agreement that these shares 'correspond' to a given flat is an arrangement between co-owners, not an official record. This is common in many areas and can be acceptable, but it means you co-own the whole property, subdivision may never happen, and any co-owner can demand the property be partitioned or sold.",
            "Die Immobilie ist nicht aufgeteilt: Das ganze Gebäude ist eine eingetragene Parzelle mit einer Anzahl Anteile (meist 2.400), und Sie kaufen Anteile, nicht eine bestimmte Wohnung im Grundbuch. Dass diese Anteile einer bestimmten Wohnung 'entsprechen', ist eine Absprache unter Miteigentümern, kein amtlicher Eintrag. Das ist in vielen Gegenden üblich und kann akzeptabel sein, bedeutet aber: Sie sind Miteigentümer des Ganzen, die Aufteilung kommt vielleicht nie, und jeder Miteigentümer kann die Aufhebung der Gemeinschaft verlangen."),
          t("قبل شراء أسهم: تأكد أن عدد الأسهم المعروض مسجّل فعلاً باسم البائع في بيان القيد، واطلب رؤية اتفاقية الشركاء إن وُجدت، واسأل عن وضع البناء من ناحية التنظيم ورخصة البناء.",
            "Before buying shares: confirm that the number of shares on offer is actually registered in the seller's name on the extract, ask to see the co-owners' agreement if one exists, and ask about the building's zoning and building permit status.",
            "Vor dem Kauf von Anteilen: Prüfen Sie, dass die angebotene Anteilszahl tatsächlich im Auszug auf den Verkäufer eingetragen ist, verlangen Sie die Miteigentümervereinbarung, falls vorhanden, und fragen Sie nach Bebauungsplan und Baugenehmigung des Gebäudes.")] },
      { h: t("حكم المحكمة", "Court ruling", "Gerichtsurteil"),
        p: [t("البائع يثبت ملكيته بحكم قضائي (غالباً حكم تثبيت بيع أو حكم قسمة) لأن العقار غير مسجّل باسمه في السجل العقاري، أو لأنه في منطقة عقارية لم تُحدَّد وتُحرَّر بعد. «حكم المحكمة الموصوف» يذكر العقار بوصف تفصيلي. الحكم القطعي وثيقة حقيقية، لكن نقل الملكية إلى اسمك في السجل قد يستغرق وقتاً أو لا يكون ممكناً حالياً. اطلب نسخة عن الحكم مع إشارة القطعية، وتحقق من صدوره فعلاً لدى المحكمة، واستعن بمحامٍ.",
            "The seller proves ownership through a court decision (often a ruling confirming a sale or a partition ruling) because the property is not registered in their name at the registry, or because it lies in a cadastral zone that has not been surveyed and registered yet. A 'described court ruling' identifies the property in detail. A final ruling is a genuine document, but transferring the property into your name at the registry may take time or may not be possible for now. Ask for a copy of the ruling with the finality note, verify at the court that it was really issued, and use a lawyer.",
            "Der Verkäufer belegt sein Eigentum mit einem Gerichtsurteil (oft Bestätigung eines Verkaufs oder Teilungsurteil), weil die Immobilie nicht auf seinen Namen eingetragen ist oder in einer noch nicht vermessenen Katasterzone liegt. Ein 'beschriebenes Urteil' bezeichnet die Immobilie genau. Ein rechtskräftiges Urteil ist ein echtes Dokument, aber die Eintragung auf Ihren Namen kann dauern oder derzeit nicht möglich sein. Verlangen Sie eine Kopie mit Rechtskraftvermerk, prüfen Sie beim Gericht, dass es wirklich ergangen ist, und nehmen Sie einen Anwalt.")] },
      { h: t("الوكالة (كاتب العدل)", "Power of attorney", "Vollmacht"),
        p: [t("يُباع العقار أحياناً بوكالة غير قابلة للعزل منظّمة لدى كاتب العدل تخوّل المشتري التصرف بالعقار. الوكالة ليست ملكية: العقار يبقى مسجلاً باسم الموكِّل، والوكالة تنتهي بوفاته ولا تمنع دائنيه من الحجز على العقار. استخدمها فقط كخطوة مؤقتة على طريق التسجيل، وحدد في العقد موعداً لنقل الملكية الفعلي.",
            "Property is sometimes sold through an irrevocable power of attorney drawn up at the notary, authorising the buyer to dispose of the property. A power of attorney is not ownership: the property stays registered in the principal's name, the power ends with their death, and it does not stop their creditors from seizing the property. Use it only as a temporary step towards registration, and fix a date for the actual transfer in the contract.",
            "Manchmal wird über eine unwiderrufliche notarielle Vollmacht verkauft, die den Käufer zur Verfügung über die Immobilie ermächtigt. Eine Vollmacht ist kein Eigentum: Die Immobilie bleibt auf den Vollmachtgeber eingetragen, die Vollmacht endet mit seinem Tod und hindert seine Gläubiger nicht an einer Pfändung. Nutzen Sie sie nur als Zwischenschritt zur Eintragung und legen Sie im Vertrag einen Termin für die tatsächliche Übertragung fest.")] },
      { h: t("بدون طابو", "No deed", "Kein Grundbuch"),
        p: [t("عقار بلا سند مسجّل ولا حكم قطعي، غالباً في مناطق السكن العشوائي أو المخالفات. ما تشتريه هو حق يد وعقد عرفي بين طرفين. السعر منخفض لسبب. لا تشترِ إلا إذا كنت تفهم المنطقة جيداً وتقبل أن حقك قد لا يُعترف به رسمياً.",
            "A property with no registered deed and no final ruling, often in informal housing areas. What you buy is possession and a private agreement between two people. The price is low for a reason. Buy only if you know the area well and accept that your right may never be officially recognised.",
            "Eine Immobilie ohne eingetragenen Titel und ohne rechtskräftiges Urteil, oft in informellen Siedlungen. Sie kaufen Besitz und einen privaten Vertrag zwischen zwei Personen. Der Preis ist aus gutem Grund niedrig. Kaufen Sie nur, wenn Sie die Gegend gut kennen und akzeptieren, dass Ihr Recht vielleicht nie amtlich anerkannt wird.")] },
    ],
    faq: [
      t(["هل الأسهم أرخص من الطابو الأخضر؟", "عادةً نعم، للشقة نفسها. الفرق يعكس المخاطر وصعوبة التصرف لاحقاً. قارن الأسعار في صفحة المنطقة على بلكون."],
        ["Are shares cheaper than green tabu?", "Usually yes, for the same apartment. The difference reflects the risk and the difficulty of selling later. Compare prices on the area page on Balkoun."],
        ["Sind Anteile billiger als grünes Grundbuch?", "Meist ja, für dieselbe Wohnung. Der Unterschied spiegelt das Risiko und die schwierigere Weiterveräußerung. Vergleichen Sie Preise auf der Gegendseite bei Balkoun."]),
      t(["هل يمكن تحويل الأسهم إلى طابو أخضر؟", "فقط عبر إفراز البناء رسمياً، وهو إجراء يحتاج موافقة الشركاء ورخصة نظامية للبناء وقد يستغرق سنوات. لا تعتمد عليه عند الشراء."],
        ["Can shares be converted to green tabu?", "Only through an official subdivision of the building, which needs the co-owners' consent and a legal building permit and can take years. Do not count on it when buying."],
        ["Können Anteile in grünes Grundbuch umgewandelt werden?", "Nur durch eine amtliche Aufteilung des Gebäudes, die die Zustimmung der Miteigentümer und eine legale Baugenehmigung braucht und Jahre dauern kann. Verlassen Sie sich beim Kauf nicht darauf."]),
    ],
  },
  {
    slug: "transfer-notary", homeIndex: 2,
    tag: t("البيع", "Selling", "Verkauf"),
    title: t("خطوات نقل الملكية: الأوراق، الرسوم، ومن يجب أن يحضر", "Transferring ownership in Syria: papers, fees, and who must be present", "Eigentumsübertragung in Syrien: Unterlagen, Gebühren und wer anwesend sein muss"),
    lede: t("من العقد الابتدائي إلى القيد باسم المشتري: ما الذي يحصل في كل خطوة، وما الذي يحتاجه البائع والمشتري كي لا يتعطّل الفراغ في اللحظة الأخيرة.",
      "From the preliminary contract to the entry in the buyer's name: what happens at each step, and what seller and buyer need so the transfer does not stall at the last minute.",
      "Vom Vorvertrag bis zur Eintragung auf den Käufer: was in jedem Schritt passiert und was Verkäufer und Käufer brauchen, damit die Übertragung nicht in letzter Minute stockt."),
    sections: [
      { h: t("العقد الابتدائي", "The preliminary contract", "Der Vorvertrag"),
        p: [t("يُوقّع الطرفان عقد بيع ابتدائي بعد التحقق من بيان القيد. يذكر العقد رقم العقار ومنطقته العقارية، الثمن الكامل، العربون المدفوع، موعد الفراغ، ومن يتحمّل الرسوم، وشرط العربون عند التراجع. يُفضّل تنظيمه لدى كاتب العدل ليكون له تاريخ ثابت وتوقيع موثّق.",
            "After checking the registry extract, both parties sign a preliminary sale contract. It states the property number and cadastral zone, the full price, the deposit paid, the transfer date, who pays which fees, and the deposit rule if someone withdraws. It is best drawn up at the notary so it has a certified date and signatures.",
            "Nach Prüfung des Grundbuchauszugs unterschreiben beide Seiten einen Vorvertrag. Er nennt Grundstücksnummer und Katasterzone, den vollen Preis, die geleistete Anzahlung, den Übertragungstermin, wer welche Gebühren trägt und die Anzahlungsregel bei Rücktritt. Am besten beim Notar, damit Datum und Unterschriften beglaubigt sind.")] },
      { h: t("الأوراق التي يجهّزها البائع", "Papers the seller prepares", "Unterlagen des Verkäufers"),
        p: [t("سند الملكية الأصلي، هوية شخصية سارية، بيان قيد عقاري حديث، وبراءات الذمة المطلوبة (المالية، البلدية، ومياه وكهرباء بحسب ما تطلبه الجهة المختصة). إذا كان العقار موروثاً، تلزم حصر الإرث ووثائق انتقال الملكية للورثة. وإذا كان البائع وكيلاً، الوكالة الأصلية سارية المفعول. تختلف القوائم بين المحافظات، فاسأل الدائرة قبل الموعد.",
            "The original deed, a valid ID, a recent registry extract, and the required clearance certificates (tax, municipality, and utilities as the office requires). If the property was inherited, the inheritance deed and the documents transferring it to the heirs are needed. If the seller is an agent, the original valid power of attorney. Lists differ between governorates, so ask the office before the appointment.",
            "Der Originaltitel, ein gültiger Ausweis, ein aktueller Grundbuchauszug und die verlangten Unbedenklichkeitsbescheinigungen (Steuer, Gemeinde, Versorger, je nach Behörde). Bei geerbtem Eigentum der Erbschein und die Übertragungsunterlagen an die Erben. Handelt ein Bevollmächtigter, die gültige Originalvollmacht. Die Listen unterscheiden sich je Gouvernement; fragen Sie vorab bei der Behörde.")] },
      { h: t("الأوراق التي يجهّزها المشتري", "Papers the buyer prepares", "Unterlagen des Käufers"),
        p: [t("هوية شخصية سارية، وإذا كان الشراء بوكالة عن شخص في الخارج، الوكالة الموثقة من السفارة أو القنصلية ومصدّقة حسب الأصول. المشتري غير السوري يحتاج موافقات خاصة تختلف بحسب الجنسية ونوع العقار، فاستشر محامياً قبل الدفع.",
            "A valid ID and, if buying under power of attorney for someone abroad, the power of attorney certified by the embassy or consulate and legalised as required. A non-Syrian buyer needs specific approvals that depend on nationality and property type, so consult a lawyer before paying.",
            "Ein gültiger Ausweis und, bei Kauf in Vollmacht für jemanden im Ausland, die von Botschaft oder Konsulat beglaubigte und legalisierte Vollmacht. Nicht-syrische Käufer brauchen je nach Staatsangehörigkeit und Immobilienart besondere Genehmigungen; fragen Sie vor der Zahlung einen Anwalt.")] },
      { h: t("يوم الفراغ", "Transfer day", "Der Tag der Übertragung"),
        p: [t("يحضر البائع (أو وكيله) والمشتري (أو وكيله) شخصياً مع الأوراق الأصلية. يُدفع باقي الثمن عادةً في اللحظة نفسها التي يُوقَّع فيها على نقل الملكية، لا قبلها. تُدفع رسوم التسجيل والطوابع بحسب التعرفة النافذة، ويتفق الطرفان مسبقاً على من يتحمّلها. بعد القيد، اطلب بيان قيد جديداً يظهر اسمك: هذه لحظة اكتمال البيع.",
            "The seller (or their agent) and the buyer (or their agent) attend in person with the original papers. The balance is normally paid at the very moment the transfer is signed, not before. Registration fees and stamp duties are paid according to the current tariff, and the parties agree in advance who bears them. After the entry, request a new extract showing your name: that is the moment the sale is complete.",
            "Verkäufer (oder Bevollmächtigter) und Käufer (oder Bevollmächtigter) erscheinen persönlich mit den Originalunterlagen. Der Restbetrag wird normalerweise genau im Moment der Unterschrift gezahlt, nicht davor. Eintragungsgebühren und Stempelsteuern richten sich nach dem geltenden Tarif; wer sie trägt, wird vorab vereinbart. Nach der Eintragung verlangen Sie einen neuen Auszug mit Ihrem Namen: Damit ist der Kauf abgeschlossen.")] },
    ],
    faq: [
      t(["كم تبلغ رسوم نقل الملكية؟", "تُحسب بحسب التعرفة الرسمية النافذة وقيمة العقار المقدّرة، وتتغيّر من وقت لآخر. اسأل الدائرة العقارية في محافظتك عن الرقم الحالي قبل أن تتفق مع البائع على من يدفعها."],
        ["How much are the transfer fees?", "They follow the official tariff in force and the assessed value of the property, and they change from time to time. Ask the registry office in your governorate for the current figure before agreeing with the seller who pays them."],
        ["Wie hoch sind die Übertragungsgebühren?", "Sie richten sich nach dem geltenden amtlichen Tarif und dem geschätzten Immobilienwert und ändern sich von Zeit zu Zeit. Fragen Sie das Grundbuchamt Ihres Gouvernements nach dem aktuellen Betrag, bevor Sie mit dem Verkäufer klären, wer sie trägt."]),
      t(["هل يجب أن أحضر بنفسي؟", "نعم، أو يحضر وكيل عنك بوكالة خاصة موثّقة تخوّله الشراء وتسجيل العقار باسمك. الوكالة العامة قد لا تكفي."],
        ["Do I have to attend in person?", "Yes, or an agent attends for you with a certified special power of attorney that authorises buying and registering in your name. A general power of attorney may not be enough."],
        ["Muss ich persönlich erscheinen?", "Ja, oder ein Bevollmächtigter erscheint mit einer beglaubigten Spezialvollmacht, die zum Kauf und zur Eintragung auf Ihren Namen ermächtigt. Eine Generalvollmacht reicht möglicherweise nicht."]),
    ],
  },
  {
    slug: "buying-from-abroad", homeIndex: 3,
    tag: t("من الخارج", "From abroad", "Aus dem Ausland"),
    title: t("كيف تشتري عقاراً في سوريا وأنت مغترب", "How to buy property in Syria while living abroad", "Immobilie in Syrien kaufen, wenn Sie im Ausland leben"),
    lede: t("ملايين السوريين في الخارج يريدون بيتاً في الوطن. الشراء عن بُعد ممكن وآمن إذا رتّبت ثلاثة أشياء: من يعاين، من يوقّع، وكيف يصل المال.",
      "Millions of Syrians abroad want a home back home. Buying remotely is possible and safe if you arrange three things: who inspects, who signs, and how the money travels.",
      "Millionen Syrer im Ausland wünschen sich ein Zuhause in der Heimat. Ein Kauf aus der Ferne ist möglich und sicher, wenn Sie drei Dinge regeln: wer besichtigt, wer unterschreibt und wie das Geld ankommt."),
    sections: [
      { h: t("المعاينة عن بُعد", "Inspecting from a distance", "Besichtigung aus der Ferne"),
        p: [t("اطلب جولة بالفيديو مباشرة (لا فيديو مسجّلاً) في أوقات مختلفة من اليوم، واسأل عن ساعات الكهرباء، وبرنامج المياه، والمولّدة والاشتراك، وحالة الدرج والمصعد، والجيران. أرسل شخصاً تثق به لزيارة ثانية بدون البائع. صور بلكون وخريطته ومتوسط سعر المتر في المنطقة تساعدك على تقييم السعر قبل أن تتفاوض.",
            "Ask for a live video tour (not a recorded one) at different times of day, and ask about electricity hours, the water schedule, the generator subscription, the state of the stairs and lift, and the neighbours. Send someone you trust for a second visit without the seller. Balkoun's photos, map and average price per square metre for the area help you judge the price before you negotiate.",
            "Bitten Sie um eine Live-Videobesichtigung (kein aufgenommenes Video) zu verschiedenen Tageszeiten und fragen Sie nach Stromstunden, Wasserplan, Generator-Abo, Zustand von Treppe und Aufzug und den Nachbarn. Schicken Sie eine Vertrauensperson zu einem zweiten Besuch ohne den Verkäufer. Fotos, Karte und Durchschnittspreis pro Quadratmeter bei Balkoun helfen, den Preis vor der Verhandlung einzuschätzen.")] },
      { h: t("من يوقّع باسمك: الوكالة", "Who signs for you: the power of attorney", "Wer für Sie unterschreibt: die Vollmacht"),
        p: [t("تحتاج إلى وكالة خاصة تنظّمها في السفارة أو القنصلية السورية في بلد إقامتك، تحدد فيها الوكيل بالاسم وتخوّله شراء العقار المحدد (أو عقار في منطقة محددة بسقف سعري) وتسجيله باسمك. اختر وكيلاً تثق به ثقة كاملة: قريب أو محامٍ. تحقق من السفارة عن المستندات والتصديقات المطلوبة والمدة، فهي تستغرق وقتاً.",
            "You need a special power of attorney drawn up at the Syrian embassy or consulate in your country of residence, naming the agent and authorising them to buy the specific property (or a property in a defined area up to a price cap) and register it in your name. Choose someone you trust completely: a relative or a lawyer. Check with the embassy what documents, legalisations and time are needed; it takes a while.",
            "Sie brauchen eine Spezialvollmacht, ausgestellt bei der syrischen Botschaft oder dem Konsulat in Ihrem Wohnsitzland, die den Bevollmächtigten namentlich nennt und ihn zum Kauf der bestimmten Immobilie (oder einer Immobilie in einer festgelegten Gegend bis zu einer Preisobergrenze) und zur Eintragung auf Ihren Namen ermächtigt. Wählen Sie jemanden, dem Sie voll vertrauen: Verwandte oder Anwalt. Erkundigen Sie sich bei der Botschaft nach Unterlagen, Beglaubigungen und Dauer; es braucht Zeit.")] },
      { h: t("كيف يصل المال", "How the money travels", "Wie das Geld ankommt"),
        p: [t("لا ترسل الثمن قبل التحقق من بيان القيد وقبل توقيع العقد الابتدائي. رتّب وصول المال بطريقة قانونية موثّقة يمكنك إثباتها لاحقاً، ونسّق مع محامٍ حول القواعد النافذة للتحويلات وإثبات مصدر الأموال. اجعل الدفع الأخير مرتبطاً بلحظة التوقيع على نقل الملكية، لا قبلها.",
            "Do not send the price before the registry extract is checked and the preliminary contract is signed. Arrange for the money to arrive through a lawful, documented channel you can prove later, and coordinate with a lawyer on the rules in force for transfers and proof of funds. Tie the final payment to the moment the transfer is signed, not before.",
            "Überweisen Sie den Preis nicht, bevor der Grundbuchauszug geprüft und der Vorvertrag unterschrieben ist. Sorgen Sie für einen legalen, dokumentierten Zahlungsweg, den Sie später nachweisen können, und stimmen Sie sich mit einem Anwalt über die geltenden Regeln für Überweisungen und Herkunftsnachweis ab. Knüpfen Sie die Schlusszahlung an den Moment der Unterschrift, nicht davor.")] },
      { h: t("الأخطاء المكلفة", "Costly mistakes", "Teure Fehler"),
        p: [t("الدفع لشخص لم تلتقِ به إلا عبر الإنترنت. الاعتماد على صور قديمة. توكيل وسيط بوكالة عامة تخوّله البيع أيضاً. شراء أسهم أو حكم محكمة بسعر طابو أخضر. إغفال براءات الذمة فيتعطّل الفراغ. والأهم: الاستعجال، فالعقار الجيد لا يختفي في يوم.",
            "Paying someone you have only met online. Relying on old photos. Giving an intermediary a general power of attorney that also lets them sell. Buying shares or a court ruling at green-tabu prices. Forgetting the clearance certificates so the transfer stalls. And above all, rushing: a good property does not vanish in a day.",
            "An jemanden zahlen, den Sie nur online kennen. Sich auf alte Fotos verlassen. Einem Vermittler eine Generalvollmacht geben, die auch zum Verkauf berechtigt. Anteile oder ein Gerichtsurteil zum Preis von grünem Grundbuch kaufen. Die Unbedenklichkeitsbescheinigungen vergessen, sodass die Übertragung stockt. Und vor allem: Eile. Eine gute Immobilie verschwindet nicht an einem Tag.")] },
    ],
    faq: [
      t(["هل يمكن تسجيل العقار باسمي وأنا خارج سوريا؟", "نعم، عبر وكيل بوكالة خاصة موثّقة من السفارة. يُسجَّل العقار باسمك أنت لا باسم الوكيل."],
        ["Can the property be registered in my name while I am outside Syria?", "Yes, through an agent holding a special power of attorney certified by the embassy. The property is registered in your name, not the agent's."],
        ["Kann die Immobilie auf meinen Namen eingetragen werden, während ich im Ausland bin?", "Ja, über einen Bevollmächtigten mit einer von der Botschaft beglaubigten Spezialvollmacht. Eingetragen wird Ihr Name, nicht der des Bevollmächtigten."]),
      t(["كيف أجد بائعاً حقيقياً؟", "على بلكون، رقم الهاتف في كل إعلان موثّق، وحالة الطابو معلنة، وبعض الأعضاء يظهرون كمكاتب معتمدة. وفي كل الأحوال: بيان قيد حديث أولاً."],
        ["How do I find a genuine seller?", "On Balkoun, the phone number on every listing is verified, the deed status is declared, and some members appear as approved agencies. In every case: a recent registry extract comes first."],
        ["Wie finde ich einen echten Verkäufer?", "Bei Balkoun ist die Telefonnummer jeder Anzeige verifiziert, der Grundbuchstatus angegeben, und manche Mitglieder erscheinen als geprüfte Büros. In jedem Fall gilt: zuerst ein aktueller Grundbuchauszug."]),
    ],
  },
  {
    slug: "renting", homeIndex: -1,
    tag: t("الإيجار", "Renting", "Miete"),
    title: t("دليل المستأجر: العقد، السلف، وما تتفقّده قبل الاستلام", "The tenant's guide to renting in Syria: contract, advance rent, and what to check before moving in", "Mieten in Syrien: Vertrag, Vorauszahlung und was Sie vor dem Einzug prüfen"),
    lede: t("الإيجار في سوريا يُدفع غالباً مقدّماً لأشهر، فالخطأ فيه مكلف. هذا ما تسأل عنه، وما تكتبه في العقد، وما تصوّره يوم الاستلام.",
      "Rent in Syria is often paid months in advance, so a mistake is expensive. Here is what to ask, what to write in the contract, and what to photograph on move-in day.",
      "Miete wird in Syrien oft für Monate im Voraus gezahlt, ein Fehler ist daher teuer. Das sollten Sie fragen, in den Vertrag schreiben und am Einzugstag fotografieren."),
    sections: [
      { h: t("تحقق من أن المؤجّر يملك حق التأجير", "Check that the landlord may let the property", "Prüfen Sie, ob der Vermieter vermieten darf"),
        p: [t("اطلب هوية المؤجّر وما يثبت ملكيته أو وكالته عن المالك. المستأجر الذي يؤجّر من الباطن دون إذن المالك قد يعرّضك للإخلاء. على بلكون، أرقام الهواتف موثّقة، وحالة الطابو ظاهرة في الإعلان.",
            "Ask for the landlord's ID and proof that they own the property or hold a power of attorney from the owner. A tenant who sublets without the owner's permission can leave you facing eviction. On Balkoun, phone numbers are verified and the deed status is shown on the listing.",
            "Verlangen Sie den Ausweis des Vermieters und einen Nachweis seines Eigentums oder seiner Vollmacht. Ein Mieter, der ohne Erlaubnis untervermietet, kann Sie in eine Räumung bringen. Bei Balkoun sind Telefonnummern verifiziert und der Grundbuchstatus steht in der Anzeige.")] },
      { h: t("ما يكتبه العقد", "What the contract must say", "Was im Vertrag stehen muss"),
        p: [t("مدة العقد وتاريخ البداية، الأجرة وعملتها وموعد دفعها، عدد أشهر السلفة والتأمين وشروط استرداده، من يدفع الكهرباء والماء والمولّدة ورسوم البناء، هل الشقة مفروشة وقائمة المفروشات، وشرط الإخلاء المبكر من الطرفين. وثّق العقد وفق الإجراءات المعمول بها في محافظتك، فالعقد الموثّق يحمي الطرفين.",
            "The term and start date, the rent, its currency and payment date, the number of months paid in advance and the deposit with its refund conditions, who pays electricity, water, generator and building charges, whether the flat is furnished and the inventory, and the early-termination rule for both sides. Register the contract according to the procedure in your governorate; a registered contract protects both parties.",
            "Laufzeit und Beginn, Miete mit Währung und Zahltag, Zahl der Vorausmonate und Kaution mit Rückzahlungsbedingungen, wer Strom, Wasser, Generator und Hausgeld zahlt, ob möbliert und mit Inventarliste, sowie die Regel für vorzeitige Kündigung beider Seiten. Lassen Sie den Vertrag nach dem Verfahren Ihres Gouvernements registrieren; ein registrierter Vertrag schützt beide Seiten.")] },
      { h: t("يوم الاستلام", "Move-in day", "Der Einzugstag"),
        p: [t("صوّر كل غرفة وكل عيب موجود، وسجّل قراءات عدادات الكهرباء والماء، واختبر الماء الساخن والصرف والأقفال والنوافذ. أرسل الصور للمؤجّر في اليوم نفسه كي تكون مؤرّخة. هذا ما يحميك عند استرداد التأمين.",
            "Photograph every room and every existing defect, record the electricity and water meter readings, and test the hot water, drains, locks and windows. Send the photos to the landlord the same day so they are dated. This is what protects your deposit later.",
            "Fotografieren Sie jeden Raum und jeden vorhandenen Mangel, notieren Sie die Zählerstände für Strom und Wasser und prüfen Sie Warmwasser, Abflüsse, Schlösser und Fenster. Schicken Sie die Fotos noch am selben Tag an den Vermieter, damit sie datiert sind. Das schützt später Ihre Kaution.")] },
      { h: t("أسئلة تطرحها قبل الاتفاق", "Questions to ask before you agree", "Fragen vor der Zusage"),
        p: [t("كم ساعة كهرباء في اليوم، وهل يوجد مولّدة وبكم الاشتراك؟ ما برنامج المياه وهل يوجد خزان؟ هل المصعد يعمل؟ ما رسوم البناء الشهرية وما الذي تغطّيه؟ هل يُسمح بالحيوانات، وهل يمكن تركيب إنترنت؟ الإجابات تُكتب في العقد لا تُقال شفهياً.",
            "How many hours of electricity a day, is there a generator and what does the subscription cost? What is the water schedule and is there a tank? Does the lift work? What are the monthly building charges and what do they cover? Are pets allowed, and can internet be installed? The answers belong in the contract, not in conversation.",
            "Wie viele Stunden Strom am Tag, gibt es einen Generator und was kostet das Abo? Wie ist der Wasserplan, gibt es einen Tank? Funktioniert der Aufzug? Wie hoch ist das monatliche Hausgeld und was deckt es? Sind Haustiere erlaubt, kann Internet installiert werden? Die Antworten gehören in den Vertrag, nicht ins Gespräch.")] },
    ],
    faq: [
      t(["كم شهراً تُدفع مقدّماً عادةً؟", "يختلف بحسب المنطقة والمؤجّر؛ كثير من العقود تطلب عدة أشهر مقدّماً مع تأمين. إعلانات الإيجار على بلكون تذكر عدد أشهر السلفة والتأمين عندما يحددها المالك."],
        ["How many months are usually paid in advance?", "It varies by area and landlord; many contracts ask for several months up front plus a deposit. Rental listings on Balkoun state the advance months and deposit when the owner sets them."],
        ["Wie viele Monate werden üblicherweise im Voraus gezahlt?", "Das hängt von Gegend und Vermieter ab; viele Verträge verlangen mehrere Monate im Voraus plus Kaution. Mietanzeigen bei Balkoun nennen Vorausmonate und Kaution, wenn der Eigentümer sie angibt."]),
      t(["هل يمكن للمؤجّر رفع الأجرة خلال العقد؟", "لا، إلا إذا نصّ العقد على ذلك صراحة. لذلك اكتب مدة العقد والأجرة بوضوح، وسجّل العقد."],
        ["Can the landlord raise the rent during the contract?", "Not unless the contract explicitly allows it. That is why the term and the rent should be written clearly, and the contract registered."],
        ["Darf der Vermieter die Miete während der Laufzeit erhöhen?", "Nicht, sofern der Vertrag es nicht ausdrücklich erlaubt. Deshalb Laufzeit und Miete klar festhalten und den Vertrag registrieren."]),
    ],
  },
];

export const GUIDE_WORDS = {
  ar: { index: "دليل المشتري والمستأجر", indexDesc: "أدلة عملية للشراء والإيجار في سوريا: التحقق من الطابو، الفرق بين الطابو الأخضر والأسهم، خطوات نقل الملكية، الشراء من الخارج، ودليل المستأجر.", eyebrow: "دليل بلكون", faqH: "أسئلة شائعة", more: "أدلة أخرى", disclaimer: "هذه الأدلة إرشادية عامة مبنية على الممارسة الشائعة، وليست استشارة قانونية. الإجراءات والرسوم تتغيّر وتختلف بين المحافظات، فاستعن بمحامٍ قبل أي دفع.", readMin: (n) => `${n} دقائق قراءة`, updated: "آخر تحديث", cta: "ابحث عن عقار الآن", crumb: "الأدلة" },
  en: { index: "Buyer's and tenant's guides for Syria", indexDesc: "Practical guides to buying and renting property in Syria: verifying a deed, green tabu versus shares, transferring ownership, buying from abroad, and renting.", eyebrow: "Balkoun guides", faqH: "Frequently asked questions", more: "More guides", disclaimer: "These guides are general information based on common practice, not legal advice. Procedures and fees change and differ between governorates, so consult a lawyer before any payment.", readMin: (n) => `${n} min read`, updated: "Last updated", cta: "Search properties now", crumb: "Guides" },
  de: { index: "Ratgeber für Käufer und Mieter in Syrien", indexDesc: "Praktische Ratgeber zum Kaufen und Mieten in Syrien: Grundbuch prüfen, grünes Grundbuch oder Anteile, Eigentumsübertragung, Kauf aus dem Ausland und Mieten.", eyebrow: "Balkoun-Ratgeber", faqH: "Häufige Fragen", more: "Weitere Ratgeber", disclaimer: "Diese Ratgeber sind allgemeine Informationen auf Basis gängiger Praxis, keine Rechtsberatung. Verfahren und Gebühren ändern sich und unterscheiden sich je Gouvernement; ziehen Sie vor jeder Zahlung einen Anwalt hinzu.", readMin: (n) => `${n} Min. Lesezeit`, updated: "Zuletzt aktualisiert", cta: "Jetzt Immobilien suchen", crumb: "Ratgeber" },
};
